$template_path = "C:\Workspaces\GitHubRoot\HostsTemplater\hosts.template"
$target_path = "C:\Workspaces\GitHubRoot\HostsTemplater\hosts"

function GetIp([String] $str) {
    $resolve = [System.Net.Dns]::GetHostAddresses($str).IPAddressToString;
    $ips = $resolve.Split(' ');
    
    if ($ips.Count -eq 1) {
        return $resolve;
    }

    $sortedIps = ($ips | ?{ $_.Length -gt 0 } | sort Length);
    $result = $sortedIps[0]; # in some cases it returns ipv4 and ipv6. Take ipv4.
    
    return $result;
}

$template = Get-Content $template_path;
$pattern = [Regex]::new('\{([\w\d_\-\.]+)\}');

$result = New-Object System.Collections.ArrayList;
$_ = $result.Add("# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!");
$_ = $result.Add("# hosts generated by EliteApps HostsTemplater at " + (Get-Date));
$_ = $result.Add("# DO NOT EDIT THIS FILE! НЕ НАДО, ПРАВДА. Используйте шаблон " + $template_path);
foreach ($line in $template) {
    $matches = $pattern.Matches($line);

    foreach ($match in $matches) {
        $ip = GetIp($match.Groups[1].Value);
        $line = $line.Replace($match, $ip);

        Write-Host "$matches => $ip";
    }
    
    $_ = $result.Add($line);
}

$result | Out-File $target_path;
